### ISSUE TITLE
Bug with long inner source

### ISSUE THREAD

**Issue by jeetiss** [Andarist/callbag-concat-map#2]
thanks for nice callbag operators ^_^

with this example

```
pipe(
  of(1),
  concatMap(() => interval(333)),
  subscribe({
    next: val => console.log(val),
    complete: () => console.log("done!"),
    error: err => console.log(err)
  })
);
```

i expect output values like `-1-2-3-4-5-`

in reality outputs `done!`

**Comment by Andarist** [comment]
Thanks for the report! I know where the bug is, need to fix it (hopefully gonna have time to work on this within few days) and release a new major version. I've implemented this operator before getting more proficient with streams & I've implemented the behaviour wrongly - it completes the inner stream when outer completes, but ofc this shouldn't happen.
